# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ouss/CLionProjects/nine-mens-morris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ouss/CLionProjects/nine-mens-morris/build-wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ouss/CLionProjects/nine-mens-morris/build-wasm/CMakeFiles /Users/ouss/CLionProjects/nine-mens-morris/build-wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ouss/CLionProjects/nine-mens-morris/build-wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nine-mens-morris

# Build rule for target.
nine-mens-morris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nine-mens-morris
.PHONY : nine-mens-morris

# fast build rule for target.
nine-mens-morris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/build
.PHONY : nine-mens-morris/fast

src/controller/board/BoardController.o: src/controller/board/BoardController.c.o
.PHONY : src/controller/board/BoardController.o

# target to build an object file
src/controller/board/BoardController.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/board/BoardController.c.o
.PHONY : src/controller/board/BoardController.c.o

src/controller/board/BoardController.i: src/controller/board/BoardController.c.i
.PHONY : src/controller/board/BoardController.i

# target to preprocess a source file
src/controller/board/BoardController.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/board/BoardController.c.i
.PHONY : src/controller/board/BoardController.c.i

src/controller/board/BoardController.s: src/controller/board/BoardController.c.s
.PHONY : src/controller/board/BoardController.s

# target to generate assembly for a file
src/controller/board/BoardController.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/board/BoardController.c.s
.PHONY : src/controller/board/BoardController.c.s

src/controller/game/GameController.o: src/controller/game/GameController.c.o
.PHONY : src/controller/game/GameController.o

# target to build an object file
src/controller/game/GameController.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/game/GameController.c.o
.PHONY : src/controller/game/GameController.c.o

src/controller/game/GameController.i: src/controller/game/GameController.c.i
.PHONY : src/controller/game/GameController.i

# target to preprocess a source file
src/controller/game/GameController.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/game/GameController.c.i
.PHONY : src/controller/game/GameController.c.i

src/controller/game/GameController.s: src/controller/game/GameController.c.s
.PHONY : src/controller/game/GameController.s

# target to generate assembly for a file
src/controller/game/GameController.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/game/GameController.c.s
.PHONY : src/controller/game/GameController.c.s

src/controller/player/PlayerController.o: src/controller/player/PlayerController.c.o
.PHONY : src/controller/player/PlayerController.o

# target to build an object file
src/controller/player/PlayerController.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/player/PlayerController.c.o
.PHONY : src/controller/player/PlayerController.c.o

src/controller/player/PlayerController.i: src/controller/player/PlayerController.c.i
.PHONY : src/controller/player/PlayerController.i

# target to preprocess a source file
src/controller/player/PlayerController.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/player/PlayerController.c.i
.PHONY : src/controller/player/PlayerController.c.i

src/controller/player/PlayerController.s: src/controller/player/PlayerController.c.s
.PHONY : src/controller/player/PlayerController.s

# target to generate assembly for a file
src/controller/player/PlayerController.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/controller/player/PlayerController.c.s
.PHONY : src/controller/player/PlayerController.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/main.c.s
.PHONY : src/main.c.s

src/model/board-node/BoardNode.o: src/model/board-node/BoardNode.c.o
.PHONY : src/model/board-node/BoardNode.o

# target to build an object file
src/model/board-node/BoardNode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board-node/BoardNode.c.o
.PHONY : src/model/board-node/BoardNode.c.o

src/model/board-node/BoardNode.i: src/model/board-node/BoardNode.c.i
.PHONY : src/model/board-node/BoardNode.i

# target to preprocess a source file
src/model/board-node/BoardNode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board-node/BoardNode.c.i
.PHONY : src/model/board-node/BoardNode.c.i

src/model/board-node/BoardNode.s: src/model/board-node/BoardNode.c.s
.PHONY : src/model/board-node/BoardNode.s

# target to generate assembly for a file
src/model/board-node/BoardNode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board-node/BoardNode.c.s
.PHONY : src/model/board-node/BoardNode.c.s

src/model/board/Board.o: src/model/board/Board.c.o
.PHONY : src/model/board/Board.o

# target to build an object file
src/model/board/Board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board/Board.c.o
.PHONY : src/model/board/Board.c.o

src/model/board/Board.i: src/model/board/Board.c.i
.PHONY : src/model/board/Board.i

# target to preprocess a source file
src/model/board/Board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board/Board.c.i
.PHONY : src/model/board/Board.c.i

src/model/board/Board.s: src/model/board/Board.c.s
.PHONY : src/model/board/Board.s

# target to generate assembly for a file
src/model/board/Board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/board/Board.c.s
.PHONY : src/model/board/Board.c.s

src/model/game/Game.o: src/model/game/Game.c.o
.PHONY : src/model/game/Game.o

# target to build an object file
src/model/game/Game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/game/Game.c.o
.PHONY : src/model/game/Game.c.o

src/model/game/Game.i: src/model/game/Game.c.i
.PHONY : src/model/game/Game.i

# target to preprocess a source file
src/model/game/Game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/game/Game.c.i
.PHONY : src/model/game/Game.c.i

src/model/game/Game.s: src/model/game/Game.c.s
.PHONY : src/model/game/Game.s

# target to generate assembly for a file
src/model/game/Game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/game/Game.c.s
.PHONY : src/model/game/Game.c.s

src/model/node/Node.o: src/model/node/Node.c.o
.PHONY : src/model/node/Node.o

# target to build an object file
src/model/node/Node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/node/Node.c.o
.PHONY : src/model/node/Node.c.o

src/model/node/Node.i: src/model/node/Node.c.i
.PHONY : src/model/node/Node.i

# target to preprocess a source file
src/model/node/Node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/node/Node.c.i
.PHONY : src/model/node/Node.c.i

src/model/node/Node.s: src/model/node/Node.c.s
.PHONY : src/model/node/Node.s

# target to generate assembly for a file
src/model/node/Node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/node/Node.c.s
.PHONY : src/model/node/Node.c.s

src/model/player/Player.o: src/model/player/Player.c.o
.PHONY : src/model/player/Player.o

# target to build an object file
src/model/player/Player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/player/Player.c.o
.PHONY : src/model/player/Player.c.o

src/model/player/Player.i: src/model/player/Player.c.i
.PHONY : src/model/player/Player.i

# target to preprocess a source file
src/model/player/Player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/player/Player.c.i
.PHONY : src/model/player/Player.c.i

src/model/player/Player.s: src/model/player/Player.c.s
.PHONY : src/model/player/Player.s

# target to generate assembly for a file
src/model/player/Player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/model/player/Player.c.s
.PHONY : src/model/player/Player.c.s

src/view/components/animation/AnimationComponent.o: src/view/components/animation/AnimationComponent.c.o
.PHONY : src/view/components/animation/AnimationComponent.o

# target to build an object file
src/view/components/animation/AnimationComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/animation/AnimationComponent.c.o
.PHONY : src/view/components/animation/AnimationComponent.c.o

src/view/components/animation/AnimationComponent.i: src/view/components/animation/AnimationComponent.c.i
.PHONY : src/view/components/animation/AnimationComponent.i

# target to preprocess a source file
src/view/components/animation/AnimationComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/animation/AnimationComponent.c.i
.PHONY : src/view/components/animation/AnimationComponent.c.i

src/view/components/animation/AnimationComponent.s: src/view/components/animation/AnimationComponent.c.s
.PHONY : src/view/components/animation/AnimationComponent.s

# target to generate assembly for a file
src/view/components/animation/AnimationComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/animation/AnimationComponent.c.s
.PHONY : src/view/components/animation/AnimationComponent.c.s

src/view/components/morris/action-button/SDLActionButton.o: src/view/components/morris/action-button/SDLActionButton.c.o
.PHONY : src/view/components/morris/action-button/SDLActionButton.o

# target to build an object file
src/view/components/morris/action-button/SDLActionButton.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/action-button/SDLActionButton.c.o
.PHONY : src/view/components/morris/action-button/SDLActionButton.c.o

src/view/components/morris/action-button/SDLActionButton.i: src/view/components/morris/action-button/SDLActionButton.c.i
.PHONY : src/view/components/morris/action-button/SDLActionButton.i

# target to preprocess a source file
src/view/components/morris/action-button/SDLActionButton.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/action-button/SDLActionButton.c.i
.PHONY : src/view/components/morris/action-button/SDLActionButton.c.i

src/view/components/morris/action-button/SDLActionButton.s: src/view/components/morris/action-button/SDLActionButton.c.s
.PHONY : src/view/components/morris/action-button/SDLActionButton.s

# target to generate assembly for a file
src/view/components/morris/action-button/SDLActionButton.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/action-button/SDLActionButton.c.s
.PHONY : src/view/components/morris/action-button/SDLActionButton.c.s

src/view/components/morris/app/App.o: src/view/components/morris/app/App.c.o
.PHONY : src/view/components/morris/app/App.o

# target to build an object file
src/view/components/morris/app/App.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/app/App.c.o
.PHONY : src/view/components/morris/app/App.c.o

src/view/components/morris/app/App.i: src/view/components/morris/app/App.c.i
.PHONY : src/view/components/morris/app/App.i

# target to preprocess a source file
src/view/components/morris/app/App.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/app/App.c.i
.PHONY : src/view/components/morris/app/App.c.i

src/view/components/morris/app/App.s: src/view/components/morris/app/App.c.s
.PHONY : src/view/components/morris/app/App.s

# target to generate assembly for a file
src/view/components/morris/app/App.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/app/App.c.s
.PHONY : src/view/components/morris/app/App.c.s

src/view/components/morris/celebrate-animation/celebrate-animation.o: src/view/components/morris/celebrate-animation/celebrate-animation.c.o
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.o

# target to build an object file
src/view/components/morris/celebrate-animation/celebrate-animation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/celebrate-animation/celebrate-animation.c.o
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.c.o

src/view/components/morris/celebrate-animation/celebrate-animation.i: src/view/components/morris/celebrate-animation/celebrate-animation.c.i
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.i

# target to preprocess a source file
src/view/components/morris/celebrate-animation/celebrate-animation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/celebrate-animation/celebrate-animation.c.i
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.c.i

src/view/components/morris/celebrate-animation/celebrate-animation.s: src/view/components/morris/celebrate-animation/celebrate-animation.c.s
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.s

# target to generate assembly for a file
src/view/components/morris/celebrate-animation/celebrate-animation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/celebrate-animation/celebrate-animation.c.s
.PHONY : src/view/components/morris/celebrate-animation/celebrate-animation.c.s

src/view/components/morris/node/UI_Node.o: src/view/components/morris/node/UI_Node.c.o
.PHONY : src/view/components/morris/node/UI_Node.o

# target to build an object file
src/view/components/morris/node/UI_Node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/node/UI_Node.c.o
.PHONY : src/view/components/morris/node/UI_Node.c.o

src/view/components/morris/node/UI_Node.i: src/view/components/morris/node/UI_Node.c.i
.PHONY : src/view/components/morris/node/UI_Node.i

# target to preprocess a source file
src/view/components/morris/node/UI_Node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/node/UI_Node.c.i
.PHONY : src/view/components/morris/node/UI_Node.c.i

src/view/components/morris/node/UI_Node.s: src/view/components/morris/node/UI_Node.c.s
.PHONY : src/view/components/morris/node/UI_Node.s

# target to generate assembly for a file
src/view/components/morris/node/UI_Node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/node/UI_Node.c.s
.PHONY : src/view/components/morris/node/UI_Node.c.s

src/view/components/morris/player/UI_Player.o: src/view/components/morris/player/UI_Player.c.o
.PHONY : src/view/components/morris/player/UI_Player.o

# target to build an object file
src/view/components/morris/player/UI_Player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/player/UI_Player.c.o
.PHONY : src/view/components/morris/player/UI_Player.c.o

src/view/components/morris/player/UI_Player.i: src/view/components/morris/player/UI_Player.c.i
.PHONY : src/view/components/morris/player/UI_Player.i

# target to preprocess a source file
src/view/components/morris/player/UI_Player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/player/UI_Player.c.i
.PHONY : src/view/components/morris/player/UI_Player.c.i

src/view/components/morris/player/UI_Player.s: src/view/components/morris/player/UI_Player.c.s
.PHONY : src/view/components/morris/player/UI_Player.s

# target to generate assembly for a file
src/view/components/morris/player/UI_Player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/player/UI_Player.c.s
.PHONY : src/view/components/morris/player/UI_Player.c.s

src/view/components/morris/popup/popup.o: src/view/components/morris/popup/popup.c.o
.PHONY : src/view/components/morris/popup/popup.o

# target to build an object file
src/view/components/morris/popup/popup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/popup/popup.c.o
.PHONY : src/view/components/morris/popup/popup.c.o

src/view/components/morris/popup/popup.i: src/view/components/morris/popup/popup.c.i
.PHONY : src/view/components/morris/popup/popup.i

# target to preprocess a source file
src/view/components/morris/popup/popup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/popup/popup.c.i
.PHONY : src/view/components/morris/popup/popup.c.i

src/view/components/morris/popup/popup.s: src/view/components/morris/popup/popup.c.s
.PHONY : src/view/components/morris/popup/popup.s

# target to generate assembly for a file
src/view/components/morris/popup/popup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/popup/popup.c.s
.PHONY : src/view/components/morris/popup/popup.c.s

src/view/components/morris/reserve-bar/ReserveBar.o: src/view/components/morris/reserve-bar/ReserveBar.c.o
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.o

# target to build an object file
src/view/components/morris/reserve-bar/ReserveBar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/reserve-bar/ReserveBar.c.o
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.c.o

src/view/components/morris/reserve-bar/ReserveBar.i: src/view/components/morris/reserve-bar/ReserveBar.c.i
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.i

# target to preprocess a source file
src/view/components/morris/reserve-bar/ReserveBar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/reserve-bar/ReserveBar.c.i
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.c.i

src/view/components/morris/reserve-bar/ReserveBar.s: src/view/components/morris/reserve-bar/ReserveBar.c.s
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.s

# target to generate assembly for a file
src/view/components/morris/reserve-bar/ReserveBar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/reserve-bar/ReserveBar.c.s
.PHONY : src/view/components/morris/reserve-bar/ReserveBar.c.s

src/view/components/morris/text-button/SdlTextButton.o: src/view/components/morris/text-button/SdlTextButton.c.o
.PHONY : src/view/components/morris/text-button/SdlTextButton.o

# target to build an object file
src/view/components/morris/text-button/SdlTextButton.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/text-button/SdlTextButton.c.o
.PHONY : src/view/components/morris/text-button/SdlTextButton.c.o

src/view/components/morris/text-button/SdlTextButton.i: src/view/components/morris/text-button/SdlTextButton.c.i
.PHONY : src/view/components/morris/text-button/SdlTextButton.i

# target to preprocess a source file
src/view/components/morris/text-button/SdlTextButton.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/text-button/SdlTextButton.c.i
.PHONY : src/view/components/morris/text-button/SdlTextButton.c.i

src/view/components/morris/text-button/SdlTextButton.s: src/view/components/morris/text-button/SdlTextButton.c.s
.PHONY : src/view/components/morris/text-button/SdlTextButton.s

# target to generate assembly for a file
src/view/components/morris/text-button/SdlTextButton.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/text-button/SdlTextButton.c.s
.PHONY : src/view/components/morris/text-button/SdlTextButton.c.s

src/view/components/morris/textarea/SdlTextArea.o: src/view/components/morris/textarea/SdlTextArea.c.o
.PHONY : src/view/components/morris/textarea/SdlTextArea.o

# target to build an object file
src/view/components/morris/textarea/SdlTextArea.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/textarea/SdlTextArea.c.o
.PHONY : src/view/components/morris/textarea/SdlTextArea.c.o

src/view/components/morris/textarea/SdlTextArea.i: src/view/components/morris/textarea/SdlTextArea.c.i
.PHONY : src/view/components/morris/textarea/SdlTextArea.i

# target to preprocess a source file
src/view/components/morris/textarea/SdlTextArea.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/textarea/SdlTextArea.c.i
.PHONY : src/view/components/morris/textarea/SdlTextArea.c.i

src/view/components/morris/textarea/SdlTextArea.s: src/view/components/morris/textarea/SdlTextArea.c.s
.PHONY : src/view/components/morris/textarea/SdlTextArea.s

# target to generate assembly for a file
src/view/components/morris/textarea/SdlTextArea.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/textarea/SdlTextArea.c.s
.PHONY : src/view/components/morris/textarea/SdlTextArea.c.s

src/view/components/morris/wallpaper/SdlWallpaper.o: src/view/components/morris/wallpaper/SdlWallpaper.c.o
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.o

# target to build an object file
src/view/components/morris/wallpaper/SdlWallpaper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/wallpaper/SdlWallpaper.c.o
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.c.o

src/view/components/morris/wallpaper/SdlWallpaper.i: src/view/components/morris/wallpaper/SdlWallpaper.c.i
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.i

# target to preprocess a source file
src/view/components/morris/wallpaper/SdlWallpaper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/wallpaper/SdlWallpaper.c.i
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.c.i

src/view/components/morris/wallpaper/SdlWallpaper.s: src/view/components/morris/wallpaper/SdlWallpaper.c.s
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.s

# target to generate assembly for a file
src/view/components/morris/wallpaper/SdlWallpaper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/morris/wallpaper/SdlWallpaper.c.s
.PHONY : src/view/components/morris/wallpaper/SdlWallpaper.c.s

src/view/components/renderer/RendererComponent.o: src/view/components/renderer/RendererComponent.c.o
.PHONY : src/view/components/renderer/RendererComponent.o

# target to build an object file
src/view/components/renderer/RendererComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/renderer/RendererComponent.c.o
.PHONY : src/view/components/renderer/RendererComponent.c.o

src/view/components/renderer/RendererComponent.i: src/view/components/renderer/RendererComponent.c.i
.PHONY : src/view/components/renderer/RendererComponent.i

# target to preprocess a source file
src/view/components/renderer/RendererComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/renderer/RendererComponent.c.i
.PHONY : src/view/components/renderer/RendererComponent.c.i

src/view/components/renderer/RendererComponent.s: src/view/components/renderer/RendererComponent.c.s
.PHONY : src/view/components/renderer/RendererComponent.s

# target to generate assembly for a file
src/view/components/renderer/RendererComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/renderer/RendererComponent.c.s
.PHONY : src/view/components/renderer/RendererComponent.c.s

src/view/components/sdl-image/SDLImageComponent.o: src/view/components/sdl-image/SDLImageComponent.c.o
.PHONY : src/view/components/sdl-image/SDLImageComponent.o

# target to build an object file
src/view/components/sdl-image/SDLImageComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-image/SDLImageComponent.c.o
.PHONY : src/view/components/sdl-image/SDLImageComponent.c.o

src/view/components/sdl-image/SDLImageComponent.i: src/view/components/sdl-image/SDLImageComponent.c.i
.PHONY : src/view/components/sdl-image/SDLImageComponent.i

# target to preprocess a source file
src/view/components/sdl-image/SDLImageComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-image/SDLImageComponent.c.i
.PHONY : src/view/components/sdl-image/SDLImageComponent.c.i

src/view/components/sdl-image/SDLImageComponent.s: src/view/components/sdl-image/SDLImageComponent.c.s
.PHONY : src/view/components/sdl-image/SDLImageComponent.s

# target to generate assembly for a file
src/view/components/sdl-image/SDLImageComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-image/SDLImageComponent.c.s
.PHONY : src/view/components/sdl-image/SDLImageComponent.c.s

src/view/components/sdl-ttf/SDLTTF.o: src/view/components/sdl-ttf/SDLTTF.c.o
.PHONY : src/view/components/sdl-ttf/SDLTTF.o

# target to build an object file
src/view/components/sdl-ttf/SDLTTF.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-ttf/SDLTTF.c.o
.PHONY : src/view/components/sdl-ttf/SDLTTF.c.o

src/view/components/sdl-ttf/SDLTTF.i: src/view/components/sdl-ttf/SDLTTF.c.i
.PHONY : src/view/components/sdl-ttf/SDLTTF.i

# target to preprocess a source file
src/view/components/sdl-ttf/SDLTTF.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-ttf/SDLTTF.c.i
.PHONY : src/view/components/sdl-ttf/SDLTTF.c.i

src/view/components/sdl-ttf/SDLTTF.s: src/view/components/sdl-ttf/SDLTTF.c.s
.PHONY : src/view/components/sdl-ttf/SDLTTF.s

# target to generate assembly for a file
src/view/components/sdl-ttf/SDLTTF.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl-ttf/SDLTTF.c.s
.PHONY : src/view/components/sdl-ttf/SDLTTF.c.s

src/view/components/sdl/SDLComponent.o: src/view/components/sdl/SDLComponent.c.o
.PHONY : src/view/components/sdl/SDLComponent.o

# target to build an object file
src/view/components/sdl/SDLComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl/SDLComponent.c.o
.PHONY : src/view/components/sdl/SDLComponent.c.o

src/view/components/sdl/SDLComponent.i: src/view/components/sdl/SDLComponent.c.i
.PHONY : src/view/components/sdl/SDLComponent.i

# target to preprocess a source file
src/view/components/sdl/SDLComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl/SDLComponent.c.i
.PHONY : src/view/components/sdl/SDLComponent.c.i

src/view/components/sdl/SDLComponent.s: src/view/components/sdl/SDLComponent.c.s
.PHONY : src/view/components/sdl/SDLComponent.s

# target to generate assembly for a file
src/view/components/sdl/SDLComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/sdl/SDLComponent.c.s
.PHONY : src/view/components/sdl/SDLComponent.c.s

src/view/components/surface/SurfaceComponent.o: src/view/components/surface/SurfaceComponent.c.o
.PHONY : src/view/components/surface/SurfaceComponent.o

# target to build an object file
src/view/components/surface/SurfaceComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/surface/SurfaceComponent.c.o
.PHONY : src/view/components/surface/SurfaceComponent.c.o

src/view/components/surface/SurfaceComponent.i: src/view/components/surface/SurfaceComponent.c.i
.PHONY : src/view/components/surface/SurfaceComponent.i

# target to preprocess a source file
src/view/components/surface/SurfaceComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/surface/SurfaceComponent.c.i
.PHONY : src/view/components/surface/SurfaceComponent.c.i

src/view/components/surface/SurfaceComponent.s: src/view/components/surface/SurfaceComponent.c.s
.PHONY : src/view/components/surface/SurfaceComponent.s

# target to generate assembly for a file
src/view/components/surface/SurfaceComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/surface/SurfaceComponent.c.s
.PHONY : src/view/components/surface/SurfaceComponent.c.s

src/view/components/texture/TextureComponent.o: src/view/components/texture/TextureComponent.c.o
.PHONY : src/view/components/texture/TextureComponent.o

# target to build an object file
src/view/components/texture/TextureComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/texture/TextureComponent.c.o
.PHONY : src/view/components/texture/TextureComponent.c.o

src/view/components/texture/TextureComponent.i: src/view/components/texture/TextureComponent.c.i
.PHONY : src/view/components/texture/TextureComponent.i

# target to preprocess a source file
src/view/components/texture/TextureComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/texture/TextureComponent.c.i
.PHONY : src/view/components/texture/TextureComponent.c.i

src/view/components/texture/TextureComponent.s: src/view/components/texture/TextureComponent.c.s
.PHONY : src/view/components/texture/TextureComponent.s

# target to generate assembly for a file
src/view/components/texture/TextureComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/texture/TextureComponent.c.s
.PHONY : src/view/components/texture/TextureComponent.c.s

src/view/components/ttf-font/FontComponent.o: src/view/components/ttf-font/FontComponent.c.o
.PHONY : src/view/components/ttf-font/FontComponent.o

# target to build an object file
src/view/components/ttf-font/FontComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/ttf-font/FontComponent.c.o
.PHONY : src/view/components/ttf-font/FontComponent.c.o

src/view/components/ttf-font/FontComponent.i: src/view/components/ttf-font/FontComponent.c.i
.PHONY : src/view/components/ttf-font/FontComponent.i

# target to preprocess a source file
src/view/components/ttf-font/FontComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/ttf-font/FontComponent.c.i
.PHONY : src/view/components/ttf-font/FontComponent.c.i

src/view/components/ttf-font/FontComponent.s: src/view/components/ttf-font/FontComponent.c.s
.PHONY : src/view/components/ttf-font/FontComponent.s

# target to generate assembly for a file
src/view/components/ttf-font/FontComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/ttf-font/FontComponent.c.s
.PHONY : src/view/components/ttf-font/FontComponent.c.s

src/view/components/utils/cleaner/Cleaner.o: src/view/components/utils/cleaner/Cleaner.c.o
.PHONY : src/view/components/utils/cleaner/Cleaner.o

# target to build an object file
src/view/components/utils/cleaner/Cleaner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/cleaner/Cleaner.c.o
.PHONY : src/view/components/utils/cleaner/Cleaner.c.o

src/view/components/utils/cleaner/Cleaner.i: src/view/components/utils/cleaner/Cleaner.c.i
.PHONY : src/view/components/utils/cleaner/Cleaner.i

# target to preprocess a source file
src/view/components/utils/cleaner/Cleaner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/cleaner/Cleaner.c.i
.PHONY : src/view/components/utils/cleaner/Cleaner.c.i

src/view/components/utils/cleaner/Cleaner.s: src/view/components/utils/cleaner/Cleaner.c.s
.PHONY : src/view/components/utils/cleaner/Cleaner.s

# target to generate assembly for a file
src/view/components/utils/cleaner/Cleaner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/cleaner/Cleaner.c.s
.PHONY : src/view/components/utils/cleaner/Cleaner.c.s

src/view/components/utils/color/Color.o: src/view/components/utils/color/Color.c.o
.PHONY : src/view/components/utils/color/Color.o

# target to build an object file
src/view/components/utils/color/Color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/color/Color.c.o
.PHONY : src/view/components/utils/color/Color.c.o

src/view/components/utils/color/Color.i: src/view/components/utils/color/Color.c.i
.PHONY : src/view/components/utils/color/Color.i

# target to preprocess a source file
src/view/components/utils/color/Color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/color/Color.c.i
.PHONY : src/view/components/utils/color/Color.c.i

src/view/components/utils/color/Color.s: src/view/components/utils/color/Color.c.s
.PHONY : src/view/components/utils/color/Color.s

# target to generate assembly for a file
src/view/components/utils/color/Color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/color/Color.c.s
.PHONY : src/view/components/utils/color/Color.c.s

src/view/components/utils/commons/Commons.o: src/view/components/utils/commons/Commons.c.o
.PHONY : src/view/components/utils/commons/Commons.o

# target to build an object file
src/view/components/utils/commons/Commons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/commons/Commons.c.o
.PHONY : src/view/components/utils/commons/Commons.c.o

src/view/components/utils/commons/Commons.i: src/view/components/utils/commons/Commons.c.i
.PHONY : src/view/components/utils/commons/Commons.i

# target to preprocess a source file
src/view/components/utils/commons/Commons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/commons/Commons.c.i
.PHONY : src/view/components/utils/commons/Commons.c.i

src/view/components/utils/commons/Commons.s: src/view/components/utils/commons/Commons.c.s
.PHONY : src/view/components/utils/commons/Commons.s

# target to generate assembly for a file
src/view/components/utils/commons/Commons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/utils/commons/Commons.c.s
.PHONY : src/view/components/utils/commons/Commons.c.s

src/view/components/window/WindowComponent.o: src/view/components/window/WindowComponent.c.o
.PHONY : src/view/components/window/WindowComponent.o

# target to build an object file
src/view/components/window/WindowComponent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/window/WindowComponent.c.o
.PHONY : src/view/components/window/WindowComponent.c.o

src/view/components/window/WindowComponent.i: src/view/components/window/WindowComponent.c.i
.PHONY : src/view/components/window/WindowComponent.i

# target to preprocess a source file
src/view/components/window/WindowComponent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/window/WindowComponent.c.i
.PHONY : src/view/components/window/WindowComponent.c.i

src/view/components/window/WindowComponent.s: src/view/components/window/WindowComponent.c.s
.PHONY : src/view/components/window/WindowComponent.s

# target to generate assembly for a file
src/view/components/window/WindowComponent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/components/window/WindowComponent.c.s
.PHONY : src/view/components/window/WindowComponent.c.s

src/view/pages/game-level-page/GameLevelPage.o: src/view/pages/game-level-page/GameLevelPage.c.o
.PHONY : src/view/pages/game-level-page/GameLevelPage.o

# target to build an object file
src/view/pages/game-level-page/GameLevelPage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/game-level-page/GameLevelPage.c.o
.PHONY : src/view/pages/game-level-page/GameLevelPage.c.o

src/view/pages/game-level-page/GameLevelPage.i: src/view/pages/game-level-page/GameLevelPage.c.i
.PHONY : src/view/pages/game-level-page/GameLevelPage.i

# target to preprocess a source file
src/view/pages/game-level-page/GameLevelPage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/game-level-page/GameLevelPage.c.i
.PHONY : src/view/pages/game-level-page/GameLevelPage.c.i

src/view/pages/game-level-page/GameLevelPage.s: src/view/pages/game-level-page/GameLevelPage.c.s
.PHONY : src/view/pages/game-level-page/GameLevelPage.s

# target to generate assembly for a file
src/view/pages/game-level-page/GameLevelPage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/game-level-page/GameLevelPage.c.s
.PHONY : src/view/pages/game-level-page/GameLevelPage.c.s

src/view/pages/home-page/HomePageView.o: src/view/pages/home-page/HomePageView.c.o
.PHONY : src/view/pages/home-page/HomePageView.o

# target to build an object file
src/view/pages/home-page/HomePageView.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/home-page/HomePageView.c.o
.PHONY : src/view/pages/home-page/HomePageView.c.o

src/view/pages/home-page/HomePageView.i: src/view/pages/home-page/HomePageView.c.i
.PHONY : src/view/pages/home-page/HomePageView.i

# target to preprocess a source file
src/view/pages/home-page/HomePageView.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/home-page/HomePageView.c.i
.PHONY : src/view/pages/home-page/HomePageView.c.i

src/view/pages/home-page/HomePageView.s: src/view/pages/home-page/HomePageView.c.s
.PHONY : src/view/pages/home-page/HomePageView.s

# target to generate assembly for a file
src/view/pages/home-page/HomePageView.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/home-page/HomePageView.c.s
.PHONY : src/view/pages/home-page/HomePageView.c.s

src/view/pages/play-mode-page/PlayModePageView.o: src/view/pages/play-mode-page/PlayModePageView.c.o
.PHONY : src/view/pages/play-mode-page/PlayModePageView.o

# target to build an object file
src/view/pages/play-mode-page/PlayModePageView.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-mode-page/PlayModePageView.c.o
.PHONY : src/view/pages/play-mode-page/PlayModePageView.c.o

src/view/pages/play-mode-page/PlayModePageView.i: src/view/pages/play-mode-page/PlayModePageView.c.i
.PHONY : src/view/pages/play-mode-page/PlayModePageView.i

# target to preprocess a source file
src/view/pages/play-mode-page/PlayModePageView.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-mode-page/PlayModePageView.c.i
.PHONY : src/view/pages/play-mode-page/PlayModePageView.c.i

src/view/pages/play-mode-page/PlayModePageView.s: src/view/pages/play-mode-page/PlayModePageView.c.s
.PHONY : src/view/pages/play-mode-page/PlayModePageView.s

# target to generate assembly for a file
src/view/pages/play-mode-page/PlayModePageView.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-mode-page/PlayModePageView.c.s
.PHONY : src/view/pages/play-mode-page/PlayModePageView.c.s

src/view/pages/play-page/playPageView.o: src/view/pages/play-page/playPageView.c.o
.PHONY : src/view/pages/play-page/playPageView.o

# target to build an object file
src/view/pages/play-page/playPageView.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-page/playPageView.c.o
.PHONY : src/view/pages/play-page/playPageView.c.o

src/view/pages/play-page/playPageView.i: src/view/pages/play-page/playPageView.c.i
.PHONY : src/view/pages/play-page/playPageView.i

# target to preprocess a source file
src/view/pages/play-page/playPageView.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-page/playPageView.c.i
.PHONY : src/view/pages/play-page/playPageView.c.i

src/view/pages/play-page/playPageView.s: src/view/pages/play-page/playPageView.c.s
.PHONY : src/view/pages/play-page/playPageView.s

# target to generate assembly for a file
src/view/pages/play-page/playPageView.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/play-page/playPageView.c.s
.PHONY : src/view/pages/play-page/playPageView.c.s

src/view/pages/rules-page/RulesPageView.o: src/view/pages/rules-page/RulesPageView.c.o
.PHONY : src/view/pages/rules-page/RulesPageView.o

# target to build an object file
src/view/pages/rules-page/RulesPageView.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/rules-page/RulesPageView.c.o
.PHONY : src/view/pages/rules-page/RulesPageView.c.o

src/view/pages/rules-page/RulesPageView.i: src/view/pages/rules-page/RulesPageView.c.i
.PHONY : src/view/pages/rules-page/RulesPageView.i

# target to preprocess a source file
src/view/pages/rules-page/RulesPageView.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/rules-page/RulesPageView.c.i
.PHONY : src/view/pages/rules-page/RulesPageView.c.i

src/view/pages/rules-page/RulesPageView.s: src/view/pages/rules-page/RulesPageView.c.s
.PHONY : src/view/pages/rules-page/RulesPageView.s

# target to generate assembly for a file
src/view/pages/rules-page/RulesPageView.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/rules-page/RulesPageView.c.s
.PHONY : src/view/pages/rules-page/RulesPageView.c.s

src/view/pages/welcome-page/WelcomePageView.o: src/view/pages/welcome-page/WelcomePageView.c.o
.PHONY : src/view/pages/welcome-page/WelcomePageView.o

# target to build an object file
src/view/pages/welcome-page/WelcomePageView.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/welcome-page/WelcomePageView.c.o
.PHONY : src/view/pages/welcome-page/WelcomePageView.c.o

src/view/pages/welcome-page/WelcomePageView.i: src/view/pages/welcome-page/WelcomePageView.c.i
.PHONY : src/view/pages/welcome-page/WelcomePageView.i

# target to preprocess a source file
src/view/pages/welcome-page/WelcomePageView.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/welcome-page/WelcomePageView.c.i
.PHONY : src/view/pages/welcome-page/WelcomePageView.c.i

src/view/pages/welcome-page/WelcomePageView.s: src/view/pages/welcome-page/WelcomePageView.c.s
.PHONY : src/view/pages/welcome-page/WelcomePageView.s

# target to generate assembly for a file
src/view/pages/welcome-page/WelcomePageView.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nine-mens-morris.dir/build.make CMakeFiles/nine-mens-morris.dir/src/view/pages/welcome-page/WelcomePageView.c.s
.PHONY : src/view/pages/welcome-page/WelcomePageView.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nine-mens-morris"
	@echo "... src/controller/board/BoardController.o"
	@echo "... src/controller/board/BoardController.i"
	@echo "... src/controller/board/BoardController.s"
	@echo "... src/controller/game/GameController.o"
	@echo "... src/controller/game/GameController.i"
	@echo "... src/controller/game/GameController.s"
	@echo "... src/controller/player/PlayerController.o"
	@echo "... src/controller/player/PlayerController.i"
	@echo "... src/controller/player/PlayerController.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/board-node/BoardNode.o"
	@echo "... src/model/board-node/BoardNode.i"
	@echo "... src/model/board-node/BoardNode.s"
	@echo "... src/model/board/Board.o"
	@echo "... src/model/board/Board.i"
	@echo "... src/model/board/Board.s"
	@echo "... src/model/game/Game.o"
	@echo "... src/model/game/Game.i"
	@echo "... src/model/game/Game.s"
	@echo "... src/model/node/Node.o"
	@echo "... src/model/node/Node.i"
	@echo "... src/model/node/Node.s"
	@echo "... src/model/player/Player.o"
	@echo "... src/model/player/Player.i"
	@echo "... src/model/player/Player.s"
	@echo "... src/view/components/animation/AnimationComponent.o"
	@echo "... src/view/components/animation/AnimationComponent.i"
	@echo "... src/view/components/animation/AnimationComponent.s"
	@echo "... src/view/components/morris/action-button/SDLActionButton.o"
	@echo "... src/view/components/morris/action-button/SDLActionButton.i"
	@echo "... src/view/components/morris/action-button/SDLActionButton.s"
	@echo "... src/view/components/morris/app/App.o"
	@echo "... src/view/components/morris/app/App.i"
	@echo "... src/view/components/morris/app/App.s"
	@echo "... src/view/components/morris/celebrate-animation/celebrate-animation.o"
	@echo "... src/view/components/morris/celebrate-animation/celebrate-animation.i"
	@echo "... src/view/components/morris/celebrate-animation/celebrate-animation.s"
	@echo "... src/view/components/morris/node/UI_Node.o"
	@echo "... src/view/components/morris/node/UI_Node.i"
	@echo "... src/view/components/morris/node/UI_Node.s"
	@echo "... src/view/components/morris/player/UI_Player.o"
	@echo "... src/view/components/morris/player/UI_Player.i"
	@echo "... src/view/components/morris/player/UI_Player.s"
	@echo "... src/view/components/morris/popup/popup.o"
	@echo "... src/view/components/morris/popup/popup.i"
	@echo "... src/view/components/morris/popup/popup.s"
	@echo "... src/view/components/morris/reserve-bar/ReserveBar.o"
	@echo "... src/view/components/morris/reserve-bar/ReserveBar.i"
	@echo "... src/view/components/morris/reserve-bar/ReserveBar.s"
	@echo "... src/view/components/morris/text-button/SdlTextButton.o"
	@echo "... src/view/components/morris/text-button/SdlTextButton.i"
	@echo "... src/view/components/morris/text-button/SdlTextButton.s"
	@echo "... src/view/components/morris/textarea/SdlTextArea.o"
	@echo "... src/view/components/morris/textarea/SdlTextArea.i"
	@echo "... src/view/components/morris/textarea/SdlTextArea.s"
	@echo "... src/view/components/morris/wallpaper/SdlWallpaper.o"
	@echo "... src/view/components/morris/wallpaper/SdlWallpaper.i"
	@echo "... src/view/components/morris/wallpaper/SdlWallpaper.s"
	@echo "... src/view/components/renderer/RendererComponent.o"
	@echo "... src/view/components/renderer/RendererComponent.i"
	@echo "... src/view/components/renderer/RendererComponent.s"
	@echo "... src/view/components/sdl-image/SDLImageComponent.o"
	@echo "... src/view/components/sdl-image/SDLImageComponent.i"
	@echo "... src/view/components/sdl-image/SDLImageComponent.s"
	@echo "... src/view/components/sdl-ttf/SDLTTF.o"
	@echo "... src/view/components/sdl-ttf/SDLTTF.i"
	@echo "... src/view/components/sdl-ttf/SDLTTF.s"
	@echo "... src/view/components/sdl/SDLComponent.o"
	@echo "... src/view/components/sdl/SDLComponent.i"
	@echo "... src/view/components/sdl/SDLComponent.s"
	@echo "... src/view/components/surface/SurfaceComponent.o"
	@echo "... src/view/components/surface/SurfaceComponent.i"
	@echo "... src/view/components/surface/SurfaceComponent.s"
	@echo "... src/view/components/texture/TextureComponent.o"
	@echo "... src/view/components/texture/TextureComponent.i"
	@echo "... src/view/components/texture/TextureComponent.s"
	@echo "... src/view/components/ttf-font/FontComponent.o"
	@echo "... src/view/components/ttf-font/FontComponent.i"
	@echo "... src/view/components/ttf-font/FontComponent.s"
	@echo "... src/view/components/utils/cleaner/Cleaner.o"
	@echo "... src/view/components/utils/cleaner/Cleaner.i"
	@echo "... src/view/components/utils/cleaner/Cleaner.s"
	@echo "... src/view/components/utils/color/Color.o"
	@echo "... src/view/components/utils/color/Color.i"
	@echo "... src/view/components/utils/color/Color.s"
	@echo "... src/view/components/utils/commons/Commons.o"
	@echo "... src/view/components/utils/commons/Commons.i"
	@echo "... src/view/components/utils/commons/Commons.s"
	@echo "... src/view/components/window/WindowComponent.o"
	@echo "... src/view/components/window/WindowComponent.i"
	@echo "... src/view/components/window/WindowComponent.s"
	@echo "... src/view/pages/game-level-page/GameLevelPage.o"
	@echo "... src/view/pages/game-level-page/GameLevelPage.i"
	@echo "... src/view/pages/game-level-page/GameLevelPage.s"
	@echo "... src/view/pages/home-page/HomePageView.o"
	@echo "... src/view/pages/home-page/HomePageView.i"
	@echo "... src/view/pages/home-page/HomePageView.s"
	@echo "... src/view/pages/play-mode-page/PlayModePageView.o"
	@echo "... src/view/pages/play-mode-page/PlayModePageView.i"
	@echo "... src/view/pages/play-mode-page/PlayModePageView.s"
	@echo "... src/view/pages/play-page/playPageView.o"
	@echo "... src/view/pages/play-page/playPageView.i"
	@echo "... src/view/pages/play-page/playPageView.s"
	@echo "... src/view/pages/rules-page/RulesPageView.o"
	@echo "... src/view/pages/rules-page/RulesPageView.i"
	@echo "... src/view/pages/rules-page/RulesPageView.s"
	@echo "... src/view/pages/welcome-page/WelcomePageView.o"
	@echo "... src/view/pages/welcome-page/WelcomePageView.i"
	@echo "... src/view/pages/welcome-page/WelcomePageView.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

